---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ChrsKng/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.  
  - atuin
  - git
  - gh
  - mas
  - node
  - nvm  
  - pnpm
  - ssh-copy-id  
  - openssl
  - yamllint
  - yt-dlp
  - zsh-history-substring-search
  - hashicorp/tap/terraform
homebrew_taps:
  - { name: hashicorp/tap}

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password-cli
  - arc
  - citrix-workspace
  - discord  
  - firefox
  - github
  - gpg-suite
  - guitar-pro
  - handbrake
  - obsidian
  - visual-studio-code
  - notion
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 1365531024, name: "1Blocker - Ad Blocker" }
  - { id: 1099568401, name: "Home Assistant" }
  - { id: 1524216218, name: "Image Tool+" }
  - { id: 1524335878, name: "Under My Roof Home Inventory +" }
  - { id: 1524216218, name: "Image Tool+" }
  - { id: 1568262835, name: "Super Agent for Safari" }
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  - { id: 639968404, name: "Parcel - Delivery Tracking" }
  - { id: 1475387142, name: "Tailscale" }  
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
